<?php
/**
 * PinPayments admin html payment form
 */

$_form = $this;
$_code = $_form->getMethodCode();
$_method = $_form->getMethod();
$_remoteAddr = Mage::helper('core/http')->getRemoteAddr(false);
?>

<ul id="payment_form_<?php echo $_code ?>" style="display:none">
    <input type="hidden" value="" id="<?php echo $_code ?>_card_token" name="payment[card_token]"/>
    <input type="hidden" value="" id="<?php echo $_code ?>_ip_address" name="payment[ip_address]"/>


    <li>
        <label for="payment[type]"><?php echo $this->__('Should this transaction be processed online or offline?') ?> <span class="required">*</span></label>
        <div class="input-box">
            <input type="radio" id="<?php echo $_code ?>_online" value="<?php echo $_method::ONLINE ?>" name="payment[type]" title="<?php echo $this->__('Online Transaction') ?>" onclick="pp.toggleTransactionType(true)" class="radio" disabled="true" />
            <label for="<?php echo $_code ?>_online"><?php echo $this->__('Online') ?></label>
            <input type="radio" id="<?php echo $_code ?>_offline" value="<?php echo $_method::OFFLINE ?>" name="payment[type]" title="<?php echo $this->__('Offline Transaction') ?>" onclick="pp.toggleTransactionType(false)" class="radio validate-one-required" disabled="true" />
            <label for="<?php echo $_code ?>_online"><?php echo $this->__('Offline') ?></label>
        </div>
    </li>

    <li style="display: none" class="offline" id="offline">
        <div class="input-box">
            <p><?php echo Mage::helper('payment')->__('Record an existing PinPayments charge against an order by supplying the PinPayments transaction Reference.')?></p>
            <label for="pinpay_id"><?php echo Mage::helper('payment')->__('PinPayments Transaction Reference') ?> <span class="required">*</span></label><br/>
            <input type="text" id="pinpay_id" name="payment[offline_transaction_id]" title="<?php echo Mage::helper('payment')->__('PinPayments Transaction Reference') ?>" class="required-entry input-text" value="" disabled="true"/>

        </div>
    </li>

    <li style="display: none" class="online" id="a">
        <label for="<?php echo $_code ?>_cc_owner"><?php echo $this->__('Name on Card') ?> <span class="required">*</span></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" value="<?php echo $this->escapeHtml($this->getInfoData('cc_owner')) ?>" disabled="true" />
        </div>
    </li>

    <li style="display: none" class="online" id="b">
        <label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?> <span class="required">*</span></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" title="<?php echo $this->__('Credit Card Number') ?>" class="required-entry input-text validate-cc-number validate-cc-type" value="" disabled="true" />
        </div>
    </li>

    <?php if ($this->isCcTypeEnabled() && $this->isCcTypeDisplayedInBackend()): ?>
    <li style="display: none" class="online" id="c">
        <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php endif;?>

    <li style="display: none" class="online" id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" class="month validate-cc-exp required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" class="year required-entry" disabled="true">
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>

    <li style="display: none" class="online" id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?> <span class="required">*</span></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" value="" disabled="true" />
            </div>
        </div>
    </li>

    <li style="display: none" class="online" id="<?php echo $_code ?>_process_transaction">
        <div class="input-box">
            <a href="#" onclick="pp.validatePinPayForm();return false"><?php echo $this->__('Validate Input') ?></a>
            <input type="hidden" id="<?php echo $_code ?>_processed" value="" class="required-entry" disabled="true">
        </div>
    </li>

</ul>

<script>

    //<![CDATA[
    var Pinpay = Class.create({

        initialize: function(){
            Pin.setPublishableKey("<?php echo $this->getPublishableKey()?>");
        },

        validatePinPayForm: function() {
            $('<?php echo $_code ?>_processed').toggleClassName('required-entry', false);
            if (!editForm.validate()) {
                $('<?php echo $_code ?>_processed').toggleClassName('required-entry', true);
                return;
            }

            var card = {
                number: $('<?php echo $_code ?>_cc_number').value,
                name: $('<?php echo $_code ?>_cc_owner').value,
                expiry_month: $('<?php echo $_code ?>_expiration').value,
                expiry_year: $('<?php echo $_code ?>_expiration_yr').value,
                cvc: $('<?php echo $_code ?>_cc_cid').value,
                address_line1: $('order-shipping_address_street0').value,
                address_line2: $('order-shipping_address_street1').value,
                address_city: $('order-shipping_address_city').value,
                address_state: $('order-shipping_address_region_id')[$('order-shipping_address_region_id').selectedIndex].text,
                address_postcode: $('order-shipping_address_postcode').value,
                address_country: $('order-shipping_address_country_id')[$('order-shipping_address_country_id').selectedIndex].text
            };
            this.setLoadWaiting(true);
            Pin.createToken(card, this.handlePinResponse.bind(this));
        },

        handlePinResponse: function(response) {
            if (response.response) {
                this.setLoadWaiting(false);

                $('<?php echo $_code ?>_card_token').value = response.response.token;
                $('<?php echo $_code ?>_ip_address').value = response.ip_address;

                alert("<?php echo $this->__('Complete. Payment ready for submission') ?>");
            } else {
                this.setLoadWaiting(false);
                alert(response.messages[0].message);
                $('<?php echo $_code ?>_processed').toggleClassName('required-entry', true);
            }
        },

        setLoadWaiting: function(enabled) {
            if(enabled) {
                var r = {options:{loadArea:''}};
                varienLoaderHandler.handler.onCreate(r);
            } else {
                varienLoaderHandler.handler.onComplete();
            }

        },

        toggleTransactionType: function(toggle) {
            $$('#payment_form_<?php echo $_code ?> li').each(function(item) {
                if(item.hasClassName('online')) {
                    this.disableChildren(item, !toggle);
                    //item.toggle(toggle); // toggle(bool) isn't working. Must use explicit methods
                    toggle ? item.show() : item.hide();
                }
                else if(item.hasClassName('offline')) {
                    this.disableChildren(item, toggle);
                    toggle ? item.hide() : item.show();
                }

                if(toggle) {
                    $('<?php echo $_code ?>_card_token').value = "";
                } else {
                    $('<?php echo $_code ?>_card_token').value = "<?php echo $this->getOfflineCardToken() ?>";
                    $('<?php echo $_code ?>_ip_address').value = "<?php echo $_remoteAddr ?>";
                }
            },
            this);

        },

        disableChildren: function(element, toggle) {
            var elements = element.select('input, select');
            elements.each(function(el) {
                el.disabled = toggle;
            });
        }
    });

    pp = new Pinpay();

    //]]>
</script>
