<?php
/**
 * PinPayments admin html payment form
 */

$_form = $this;
$_code = $_form->getMethodCode();
$_method = $_form->getMethod();
$_remoteAddr = Mage::helper('core/http')->getRemoteAddr(false);
?>

<ul id="payment_form_<?php echo $_code ?>" style="display:none">

    <input type="hidden" value="" id="<?php echo $_code ?>_card_token" name="payment[card_token]"/>
    <li>
        <label for="payment[type]"><?php echo $this->__('Should this transaction be processed online or offline?') ?> <span class="required">*</span></label>
        <div class="input-box">
            <input type="radio" id="<?php echo $_code ?>_online" value="<?php echo $_method::ONLINE ?>" name="payment[type]" title="<?php echo $this->__('Online Transaction') ?>" onclick="ppToggle.toggleTransactionType(true)" class="radio" disabled="true" />
            <label for="<?php echo $_code ?>_online"><?php echo $this->__('Online') ?></label>
            <input type="radio" id="<?php echo $_code ?>_offline" value="<?php echo $_method::OFFLINE ?>" name="payment[type]" title="<?php echo $this->__('Offline Transaction') ?>" onclick="ppToggle.toggleTransactionType(false)" class="radio validate-one-required" disabled="true" />
            <label for="<?php echo $_code ?>_online"><?php echo $this->__('Offline') ?></label>
        </div>
    </li>

    <li style="display: none" class="offline" id="offline">
        <div class="input-box">
            <p><?php echo Mage::helper('payment')->__('Record an existing PinPayments charge against an order by supplying the PinPayments transaction Reference.')?></p>
            <label for="pinpay_id"><?php echo Mage::helper('payment')->__('PinPayments Transaction Reference') ?> <span class="required">*</span></label><br/>
            <input type="text" id="pinpay_id" name="payment[offline_transaction_id]" title="<?php echo Mage::helper('payment')->__('PinPayments Transaction Reference') ?>" class="required-entry input-text" value="" disabled="true"/>

        </div>
    </li>

    <li style="display: none" class="online" id="a">
        <div id="hosted-card-fields">

        </div>
    </li>

    <li style="display: none" class="online" id="<?php echo $_code ?>_process_transaction">
        <div class="input-box">
            <a href="#" onclick="pp.validatePinPayForm(); return false"><?php echo $this->__('Validate Input') ?></a>
            <input type="hidden" id="<?php echo $_code ?>_processed" value="" class="required-entry" disabled="true">
        </div>
    </li>


</ul>

<script>

    var PinpayToggle = Class.create({

        toggleTransactionType: function (toggle) {
            $$('#payment_form_<?php echo $_code ?> li').each(function (item) {
                    if (item.hasClassName('online')) {
                        this.disableChildren(item, !toggle);
                        toggle ? item.show() : item.hide();
                    }
                    else if (item.hasClassName('offline')) {
                        this.disableChildren(item, toggle);
                        toggle ? item.hide() : item.show();
                    }

                    if(toggle) {
                        $('<?php echo $_code ?>_card_token').value = "";
                    } else {
                        $('<?php echo $_code ?>_card_token').value = "<?php echo $this->getOfflineCardToken() ?>";
                    }
                },
                this);
        },

        removeValidation: function() {
            $('<?php echo $_code ?>_processed').removeClassName('required-entry');
            alert("<?php echo $this->__('Payment ready for submission') ?>");
        },

        disableChildren: function (element, toggle) {
            var elements = element.select('input, select');
            elements.each(function (el) {
                el.disabled = toggle;
            });
        }
    });

    ppToggle = new PinpayToggle();

    pp = new PinpayHosted(
        {
            token_element: '<?php echo $_code ?>_card_token',
            api_env: '<?php echo $this->getEnvironment() ?>',
            api_key: '<?php echo $this->getPublishableKey() ?>',
            form_element_id: 'payment_form_<?php echo $_code ?>',
            hosted_fields_element_id: 'hosted-card-fields',
            values: {
                address_line1: $('order-shipping_address_street0').value,
                address_line2: $('order-shipping_address_street1').value,
                address_city: $('order-shipping_address_city').value,
                address_state: $('order-shipping_address_region_id')[$('order-shipping_address_region_id').selectedIndex].text,
                address_postcode: $('order-shipping_address_postcode').value,
                address_country: $('order-shipping_address_country_id')[$('order-shipping_address_country_id').selectedIndex].text
            },
            style: [".CardFields--address_line1 { display: none; }",".CardFields--address_line2 { display: none; }",".CardFieldsGroup--city-state-postcode { display: none; }", ".CardFields input { font-size: 18px; }", ".CardFields label { display: none; }", ".CardFields--expiry input { width: 90px; }", ".CardFields--cvc input { width: 90px; }", ".CardFields--expiry, .CardFields--cvc {display: inline-block; }", ".Errors { color: red; font-size: 12px }"]
        },
        '<?php echo $this->getHostedIframeUrl() ?>',
        ppToggle.removeValidation
    );

</script>
