var PinpayHosted = Class.create({

  /** Token generated by Card Token API */
  token: null,
  form: null,
  field_container: null,
  iframe: null,


  initialize: function(config){
    debugger;

    this.form = document.getElementById(config.form_element_id);
    this.field_container = document.getElementById(config.hosted_fields_element_id);

    // create the iframe
    this.iframe = document.createElement('iframe');
    this.config = config;
    this.iframe.setAttribute('src', "http://pinpayments.github.io/sensis/hosted-fields.html");
    Event.observe(this.iframe, "load", this.handleIframeLoad.bind(this));
    this.field_container.appendChild(this.iframe);
    Event.observe(window, 'message', this.receiveMessage.bind(this));
  },

  handleIframeLoad: function() {
    var configMessage = {
      config: this.config
    };
    this.iframe.contentWindow.postMessage(JSON.stringify(configMessage), "*");
  },

  validatePinPayForm: function() {
    this.iframe.contentWindow.postMessage('set-token', "*");
    return false;
  },

  receiveMessage: function(e) {
    // if the user presses the enter key in the iframe form,
    // we'll receive a 'submit' message here.
    if (e.data.lastIndexOf('submit', 0) === 0) {
      this.form.submit();
    } else {
      // messages other than 'submit' are card tokens.
      // populate the token field
      $(this.config.token_element).value = e.data;
      // submit the form (the delay is just for the demo)
      setTimeout(function () {
        //form.submit();
        payment.save(true);
      }, 1000);
    }
  }

});