
<?php
/** @var $this Dwyera_Pinpay_Block_Form */

$_form = $this;
$_code = $_form->getMethodCode();
$_method = $_form->getMethod();

?>


<!-- normal form-->
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <input type="hidden" value="" id="<?php echo $_code ?>_card_token" name="payment[card_token]"/>
    <input type="hidden" value="" id="<?php echo $_code ?>_ip_address" name="payment[ip_address]"/>

    <form id='<?php echo $_code ?>_direct_form' action="#" method='post'>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" value="<?php echo $this->escapeHtml($this->getInfoData('cc_owner')) ?>" />
            </div>
        </li>

        <li>
            <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
            <div class="input-box">
                <input type="text" id="<?php echo $_code ?>_cc_number" title="<?php echo $this->__('Credit Card Number') ?>" class="required-entry input-text validate-cc-number validate-cc-type" value="" />
            </div>
        </li>

        <li id="<?php echo $_code ?>_cc_type_exp_div">
            <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_expiration" class="month validate-cc-exp required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                    <select id="<?php echo $_code ?>_expiration_yr" class="year required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>

        <li id="<?php echo $_code ?>_cc_type_cvv_div">
            <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" value="" />
                </div>
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
            </div>
        </li>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_address_line1" class="required"><em>*</em><?php echo $this->__('Address Line 1') ?></label>
                <input type="text" title="<?php echo $this->__('Address Line 1') ?>" class="input-text required-entry" id="<?php echo $_code ?>_address_line1" value="" />
            </div>
        </li>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_address_line2"><?php echo $this->__('Address Line 2') ?></label>
                <input type="text" title="<?php echo $this->__('Address Line 2') ?>" class="input-text" id="<?php echo $_code ?>_address_line2" value="" />
            </div>
        </li>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_address_city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                <input type="text" title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="<?php echo $_code ?>_address_city" value="" />
            </div>
        </li>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_address_state" class="required"><em>*</em><?php echo $this->__('State') ?></label>
                <input type="text" title="<?php echo $this->__('State') ?>" class="input-text required-entry" id="<?php echo $_code ?>_address_state" value="" />
            </div>
        </li>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_address_postcode" class="required"><em>*</em><?php echo $this->__('Postcode') ?></label>
                <input type="text" title="<?php echo $this->__('Postcode') ?>" class="input-text required-entry validate-zip-international" id="<?php echo $_code ?>_address_postcode" value="" />
            </div>
        </li>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_address_country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                <input type="text" title="<?php echo $this->__('Country') ?>" class="input-text required-entry" id="<?php echo $_code ?>_address_country" value="" />
            </div>
        </li>

        <input type='submit' value='Pay now' id='submitbtn' />
    </form>
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>

<script type="text/javascript">

    var Pinpay = Class.create({

        /** Token generated by Card Token API */
        token: null,
        /** IP address of client recorded by Card Token API */
        ip_address: null,

        initialize: function(){
            Pin.setPublishableKey("<?php echo $this->getPublishableKey()?>");
            //var inputs = $('<?php echo $_code ?>_direct_form').getInputs();
            //for(var i = 0; i<inputs.length;i++) {inputs[i].disabled = false;}

            // TODO clean up these anon listeners
            document.observe("payment-method:switched", function(event) {

                if(event.memo.method_code == "<?php echo $_code ?>" && this.token == null) {
                    this.toggleSubmit(true);
                } else {
                    this.toggleSubmit(false);
                }
            }.bind(this));

            $('<?php echo $_code ?>_direct_form').observe('submit', function(e) {
                e.stop();

                var validator = new Validation(payment.form);
                if (!validator.validate()) {
                    return;
                }

                var card = {
                    number: $('<?php echo $_code ?>_cc_number').value,
                    name: $('<?php echo $_code ?>_cc_owner').value,
                    expiry_month: $('<?php echo $_code ?>_expiration').value,
                    expiry_year: $('<?php echo $_code ?>_expiration_yr').value,
                    cvc: $('<?php echo $_code ?>_cc_cid').value,
                    address_line1: $('<?php echo $_code ?>_address_line1').value,
                    address_line2: $('<?php echo $_code ?>_address_line2').value,
                    address_city: $('<?php echo $_code ?>_address_city').value,
                    address_state: $('<?php echo $_code ?>_address_state').value,
                    address_postcode: $('<?php echo $_code ?>_address_postcode').value,
                    address_country: $('<?php echo $_code ?>_address_country').value
                };

                Pin.createToken(card, this.handlePinResponse.bind(this));
            }.bind(this));
        },

        toggleSubmit: function(disabled) {
            var submitButton = $('payment-buttons-container').select('button')[0];
            if(disabled === true) {
                submitButton.addClassName('disabled');
            } else {
                submitButton.removeClassName('disabled');
            }
        },

        handlePinResponse: function(response) {
            if (response.response) {

                this.token = response.response.token;
                this.ip_address = response.ip_address;

                var card = $('<?php echo $_code ?>_card_token');
                card.value = this.token;

                var ip = $('<?php echo $_code ?>_ip_address');
                ip.value = this.ip_address;

                console.log(response.response.token);
                this.toggleSubmit(false);

            } else {
                alert(response.error_description);
            }
        }

    });

    var pp = new Pinpay();

</script>
