
<?php
/** @var $this Dwyera_Pinpay_Block_Form */

$_form = $this;
$_code = $_form->getMethodCode();
$_method = $_form->getMethod();
$_billingAddress = $this->getBillingAddress();
$pinpaymentCustomerToken = "";
if(Mage::getSingleton('customer/session')->isLoggedIn() && $this->iscustomerTokenizationEnabled()){
    $customer_data = Mage::getSingleton('customer/session')->getCustomer();
    $pinpaymentCustomerToken = $customer_data->getData('pinpayment_customer_token');
    $pinpaymentCardDisplayNumber = $customer_data->getData('pinpayment_card_display_number');
}
$isPinpaymentCustomerUseExisting = false;
if($pinpaymentCustomerToken != "") {
    $isPinpaymentCustomerUseExisting = true;
}
?>


<!-- normal form-->
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <input type="hidden" value="" id="<?php echo $_code ?>_card_token" name="payment[card_token]"/>
    <input type="hidden" value="" id="<?php echo $_code ?>_ip_address" name="payment[ip_address]"/>
    <input type="hidden" value="" id="<?php echo $_code ?>_card_action" name="payment[card_action]"/>
    <input type="hidden" value="<?php echo isset($pinpaymentCustomerToken)? $pinpaymentCustomerToken:"" ?>" id="<?php echo $_code ?>_customer_token" name="payment[customer_token]"/>


    <?php if ($this->iscustomerTokenizationEnabled()): ?>
        <?php if($isPinpaymentCustomerUseExisting): ?>
            <li>
                <div class="input-box">
                    <input type="radio" name="card_details" class="js-card_details" id="<?php echo $_code ?>_use_existing_card" value="true" checked="checked"> Use saved card details - <?php echo $pinpaymentCardDisplayNumber;?><br>
                    <input type="radio" name="card_details" class="js-card_details" id="<?php echo $_code ?>_update_new_card" value="true"> Update and pay with new details. <br>
                </div>
            </li>
        <?php else:?>
            <li>
                <div class="input-box">
                    <input type="radio" id="<?php echo $_code ?>_save_card" value="true"> Save credit card details<br>
                </div>
            </li>
        <?php endif; ?>
    <?php endif;?>


    <li class="js-card_details_rows"<?php if($isPinpaymentCustomerUseExisting): ?> style="display: none"<?php endif; ?>>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text <?php if($isPinpaymentCustomerUseExisting): ?>original-<?php endif; ?>required-entry" id="<?php echo $_code ?>_cc_owner" value="<?php echo $this->escapeHtml($this->getInfoData('cc_owner')) ?>"<?php if($isPinpaymentCustomerUseExisting): ?> disabled="disabled"<?php endif; ?> />
        </div>
    </li>

    <li class="js-card_details_rows"<?php if($isPinpaymentCustomerUseExisting): ?> style="display: none"<?php endif; ?>>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" title="<?php echo $this->__('Credit Card Number') ?>" class="<?php if($isPinpaymentCustomerUseExisting): ?>original-<?php endif; ?>required-entry input-text validate-cc-number validate-cc-type" value=""<?php if($isPinpaymentCustomerUseExisting): ?> disabled="disabled"<?php endif; ?> />
        </div>
    </li>

    <?php if ($this->isCcTypeEnabled() && $this->isCcTypeDisplayedInFrontend()): ?>
    <li class="js-card_details_rows"<?php if($isPinpaymentCustomerUseExisting): ?> style="display: none"<?php endif; ?>>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="<?php if($isPinpaymentCustomerUseExisting): ?>original-<?php endif; ?>required-entry validate-cc-type-select"<?php if($isPinpaymentCustomerUseExisting): ?> disabled="disabled"<?php endif; ?>>
                <option value=""><?php echo $this->__('--Please Select--')?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php endif;?>

    <li id="<?php echo $_code ?>_cc_type_exp_div" class="js-card_details_rows"<?php if($isPinpaymentCustomerUseExisting): ?> style="display: none"<?php endif; ?>>
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" class="month validate-cc-exp <?php if($isPinpaymentCustomerUseExisting): ?>original-<?php endif; ?>required-entry"<?php if($isPinpaymentCustomerUseExisting): ?> disabled="disabled"<?php endif; ?>>
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" class="year <?php if($isPinpaymentCustomerUseExisting): ?>original-<?php endif; ?>required-entry"<?php if($isPinpaymentCustomerUseExisting): ?> disabled="disabled"<?php endif; ?>>
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>

    <li id="<?php echo $_code ?>_cc_type_cvv_div" class="js-card_details_rows"<?php if($isPinpaymentCustomerUseExisting): ?> style="display: none"<?php endif; ?>>
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv <?php if($isPinpaymentCustomerUseExisting): ?>original-<?php endif; ?>required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" value=""<?php if($isPinpaymentCustomerUseExisting): ?> disabled="disabled"<?php endif; ?> />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>

    <li class="hidden-address-fields">
        <div class="input-box">
            <label for="<?php echo $_code ?>_address_line1" class="required"><em>*</em><?php echo $this->__('Address Line 1') ?></label>
            <input type="text" title="<?php echo $this->__('Address Line 1') ?>" class="input-text required-entry" id="<?php echo $_code ?>_address_line1" value="<?php echo $_billingAddress->getStreet1() ?>" />
        </div>
    </li>

    <li class="hidden-address-fields">
        <div class="input-box">
            <label for="<?php echo $_code ?>_address_line2"><?php echo $this->__('Address Line 2') ?></label>
            <input type="text" title="<?php echo $this->__('Address Line 2') ?>" class="input-text" id="<?php echo $_code ?>_address_line2" value="<?php echo $_billingAddress->getStreet2() ?>" />
        </div>
    </li>

    <li class="hidden-address-fields">
        <div class="input-box">
            <label for="<?php echo $_code ?>_address_city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
            <input type="text" title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="<?php echo $_code ?>_address_city" value="<?php echo $_billingAddress->getCity() ?>" />
        </div>
    </li>

    <li class="hidden-address-fields">
        <div class="input-box">
            <label for="<?php echo $_code ?>_address_state"><?php echo $this->__('State') ?></label>
            <input type="text" title="<?php echo $this->__('State') ?>" class="input-text" id="<?php echo $_code ?>_address_state" value="<?php echo $_billingAddress->getRegion() ?>" />
        </div>
    </li>

    <li class="hidden-address-fields">
        <div class="input-box">
            <label for="<?php echo $_code ?>_address_postcode"><?php echo $this->__('Postcode') ?></label>
            <input type="text" title="<?php echo $this->__('Postcode') ?>" class="input-text validate-zip-international" id="<?php echo $_code ?>_address_postcode" value="<?php echo $_billingAddress->getPostcode() ?>" />
        </div>
    </li>

    <li class="hidden-address-fields">
        <div class="input-box">
            <label for="<?php echo $_code ?>_address_country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
            <input type="text" title="<?php echo $this->__('Country') ?>" class="input-text required-entry" id="<?php echo $_code ?>_address_country" value="<?php echo $_billingAddress->getCountryModel()->getName() ?>" />
        </div>
    </li>
    <li>
        <div class="buttons-set" id="pinpay-buttons-container">
        <!--<div id="pinpay-submit" class="v-fix">
            <input type='submit' value='Validate Card' id='pinpay-submit-btn' />
        </div>-->
        <span id="pinpay-please-wait" class="please-wait" style="display: none;">
            <img src="<?php echo $this->getSkinUrl("/images/opc-ajax-loader.gif")?>" alt="Please wait" title="Validating Card..." class="v-middle">Validating Card...        </span>
        </div>
    </li>
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>

<script type="text/javascript">
    $('payment_form_<?php echo $_code ?>').on('change', '.js-card_details', function(event) {
        var cssSelector = '#payment_form_<?php echo $_code ?> .required-entry, #payment_form_<?php echo $_code ?> .original-required-entry';
        if (event.target.id == 'pinpay_use_existing_card') {
            $$(cssSelector).each(function (requiredElement) {
                if (!requiredElement.hasClassName('original-required-entry')) {
                    requiredElement.addClassName('original-required-entry').removeClassName('required-entry');
                    requiredElement.setAttribute('disabled', 'disabled');
                };
            });
            $$('.js-card_details_rows').invoke('hide');
        } else {
            $$(cssSelector).each(function (requiredElement) {
                if (requiredElement.hasClassName('original-required-entry')) {
                    requiredElement.addClassName('required-entry').removeClassName('original-required-entry');
                    requiredElement.removeAttribute('disabled');
                };
            });
            $$('.js-card_details_rows').invoke('show');
        }
    });

    //<![CDATA[
    var Pinpay = Class.create({

        /** Token generated by Card Token API */
        token: null,
        /** IP address of client recorded by Card Token API */
        ip_address: null,

        initialize: function(){
            Pin.setPublishableKey("<?php echo $this->getPublishableKey()?>");
            this.attachValidationCallBackFunction('payment_form_<?php echo $_code ?>');
        },
        attachValidationCallBackFunction: function(containerId){
            var cssSelector = '#' + containerId + ' .required-entry';
            //attach validation callback for all the required pinpay hidden elements
            $$(cssSelector).each(function(requiredElement) {
                requiredElement.callbackFunction = "pinPaymentValidationCallBack";
            }.bind(this));
        },
        validatePinPayForm: function() {
            var customer_token = $('<?php echo $_code ?>_customer_token').value;
            if($('<?php echo $_code ?>_use_existing_card') && $('<?php echo $_code ?>_use_existing_card').checked === true ){
                checkout.setLoadWaiting(false);

                var use_existing_card = $('<?php echo $_code ?>_card_action');
                use_existing_card.value = "use_existing_card";

                var customer = $('<?php echo $_code ?>_customer_token');
                customer.value = customer_token;

                var ip = $('<?php echo $_code ?>_ip_address');
                this.ip_address = "<?php echo Mage::helper('core/http')->getRemoteAddr(true); ?>";
                ip.value = this.ip_address;

                payment.save(true);
            } else {
                var validator = new Validation(payment.form);
                if (!validator.validate()) {
                    return;
                }

                var card = {
                    number: $('<?php echo $_code ?>_cc_number').value,
                    name: $('<?php echo $_code ?>_cc_owner').value,
                    expiry_month: $('<?php echo $_code ?>_expiration').value,
                    expiry_year: $('<?php echo $_code ?>_expiration_yr').value,
                    cvc: $('<?php echo $_code ?>_cc_cid').value,
                    address_line1: $('<?php echo $_code ?>_address_line1').value,
                    address_line2: $('<?php echo $_code ?>_address_line2').value,
                    address_city: $('<?php echo $_code ?>_address_city').value,
                    address_state: $('<?php echo $_code ?>_address_state').value,
                    address_postcode: $('<?php echo $_code ?>_address_postcode').value,
                    address_country: $('<?php echo $_code ?>_address_country').value
                };
                checkout.setLoadWaiting('pinpay');
                Pin.createToken(card, this.handlePinResponse.bind(this));
            }
        },

        handlePinResponse: function(response) {
            if (response.response) {
                checkout.setLoadWaiting(false);
                this.token = response.response.token;
                this.ip_address = response.ip_address;

                if($('<?php echo $_code ?>_update_new_card') && $('<?php echo $_code ?>_update_new_card').checked == true) {
                    $('<?php echo $_code ?>_card_action').value = "update_new_card";
                }
                if($('<?php echo $_code ?>_save_card') && $('<?php echo $_code ?>_save_card').checked == true) {
                    $('<?php echo $_code ?>_card_action').value = "save_card";
                }
                var customer_token = $('<?php echo $_code ?>_customer_token').value;

                var customer = $('<?php echo $_code ?>_customer_token');
                customer.value = customer_token;

                var card = $('<?php echo $_code ?>_card_token');
                card.value = this.token;

                var ip = $('<?php echo $_code ?>_ip_address');
                ip.value = this.ip_address;

                payment.save(true);

            } else {
                checkout.setLoadWaiting(false);
                var message;
                message = 'Unable to process pin payment. Please contact support';
                try {
                    //non-api error messages
                    message = response.messages[0].message;
                }
                catch(err){
                    try{
                        //if property is not defined concatenating it with string results in 'undefinedDefinedString'
                        var errorDescription = response.error_description ? response.error_description : '';
                        var errorTitle = response.error ? response.error : '';
                        //pin payment error response in cases when api keys are not right
                        //if either error or description is present construct error message, otherwise use default message
                        // https://pin.net.au/docs/api look at Errors section of page
                        if (errorTitle|| errorDescription){
                            var separator = (errorTitle && errorDescription) ? ': ' : '';
                            message = errorTitle + separator + errorDescription;
                        }
                    }
                    catch(error){
                        console.log(error);
                    }
                }
                alert(message);
            }
        }
    });

    pp = new Pinpay();

    var PPPayment = Class.create(Payment, {
        save: function($super, validated) {
            // Ignore this overridden method if the current method isn't PinPay
            if(this.currentMethod != "<?php echo $_code ?>") {
                $super();
                return;
            }
            // only call the the parents save function if the PinPayment form has already been validated
            if(validated) {
                $super();
            } else {
                pp.validatePinPayForm();
            }
        }
    });

    // override the default payment class
    payment = new PPPayment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    //]]>
    /**
     * prototype callback works only with global name space function
     * @see Validator::updateCallback()
     *    eval(elm.callbackFunction+'(\''+elm.id+'\',\''+status+'\')');
     *
     * @param elementId
     * @param status
     */
    window.pinPaymentValidationCallBack = function (elementId, status){
        if (status == 'failed'){
            var element = $(elementId);
            var title  = element.title ? element.title : element.id;
            var message = 'Pin pay requires ' + title + ' for payment';
            if (!title){
                message = "Please provide all fields required by pin pay";
            }
            alert(message);
        }
    }
</script>
